id: P010430
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:49:30.168132
source_metadata:
  id: bdr:W2MS743
  title: དགེ་འདུན་ཆོས་འཕེལ
  author: ''
  volumes:
    cc1a053dca714157a672d98bded9ae28:
      image_group_id: I00KG09986
      title: ''
      volume_number: 1
      total_pages: 330
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
